export const labels = {
  sourceRecords: 'Source Records',
  selectedSourceRecords: 'Selected Source Records',
  weeklyCoverageRecords: 'Weekly Coverage Records',
  fiscalWeeks: 'Fiscal Weeks',
  firstWeekEnding: 'First Week Ending',
  latestWeekEnding: 'Latest Week Ending',
  stores: 'Stores',
  metrics: 'Metrics',
  storesMissingTradingCommencementDate: 'Stores Missing Trading Commencement Date',
  storesWithClosureDate: 'Stores With Closure Date',
  selectedStore: 'Selected Store',
  selectedMetric: 'Selected Metric',
  selectedPeriodLens: 'Selected Period Lens',
  currentComparableWeeks: 'Current Comparable Weeks',
  priorComparableWeeks: 'Prior Comparable Weeks',
  firstComparableWeek: 'First Comparable Week',
  latestComparableWeek: 'Latest Comparable Week',
  storeTradingDateWarnings: 'Store Trading Date Warnings',
  storeClosureStatus: 'Store Closure Status',
  sourceRecordsMatched: 'Source Records Matched',
  weeksWithoutSourceData: 'Weeks Without Source Data',
  manualCoverageAdjustments: 'Manual Coverage Adjustments',
  manualCoverageAdjustmentsApplied: 'Manual Coverage Adjustments Applied',
  weeksNotExpectedToTrade: 'Weeks Not Expected to Trade',
  includedComparableWeeks: 'Included Comparable Weeks',
  excludedComparableWeeks: 'Excluded Comparable Weeks',
  periodLens: 'Period Lens',
  comparisonSide: 'Comparison Side',
  comparableSlot: 'Comparable Slot',
  fiscalWeek: 'Fiscal Week',
  fiscalMonth: 'Fiscal Month',
  weeklyMetricValue: 'Weekly Metric Value',
  sourceDataStatus: 'Source Data Status',
  tradingExpectation: 'Trading Expectation',
  manualCoverageAdjustment: 'Manual Coverage Adjustment',
  coverageDecision: 'Coverage Decision',
  finalCcmOutcome: 'Final CCM Outcome',
  outcomeReason: 'Outcome Reason',
  alignmentImpact: 'Alignment Impact',
  comparableWeekRecords: 'Comparable Week Records',
  previousMaskRecordsCleared: 'Previous Mask Records Cleared',
  maskRecordsWritten: 'Mask Records Written',
  dateQualityWarnings: 'Date Quality Warnings',
  comparableWeekRecordsToWrite: 'Comparable Week Records to Write',
  generationMode: 'Generation Mode',
  outputCollection: 'Output Collection',
  runId: 'Run ID',
  rebuildStatus: 'Rebuild Status'
};

export const helperText = {
  sourceRecords: 'Source Records are raw rows from the mapped source dataset.',
  weeklyCoverageRecords: 'Weekly Coverage Records are aggregated to Store × Metric × Fiscal Week, which is the grain used by the CCM decision logic.',
  comparableWeekCounts: 'Included and excluded counts refer to comparable weeks, not raw source rows.',
  tradingExpectation: 'Trading Expectation is determined from store trading commencement and closure dates. The displayed Y/N value is the underlying system flag.',
  selectedScopeMask: 'This rebuilds the selected-scope CCM output for the current Store, Metric, and Period Lens only. It is intended for Phase 1 validation, not production full-mask processing.',
  maskScope: 'Selected Scope Mask is for Phase 1 validation only. Full CCM Mask is reserved for production.',
  selectedScopeClear: 'Existing selected-scope mask records will be cleared before selected-scope records are written. Manual coverage adjustments will not be affected.'
};

export const displayText = {
  selectedScopeOutput: 'Output: Selected Scope Mask',
  selectedScopeCollection: 'AppDB collection: ccm_selected_scope_mask',
  fullMaskOutput: 'Output: Full CCM Mask',
  fullMaskCollection: 'AppDB collection: ccm_full_mask',
  fullMaskStatus: 'Status: Coming soon / planned for production',
  businessValidation: 'Business Validation',
  technicalWriteSummary: 'Technical Write Summary',
  week53OutcomeReason: 'Week 53 excluded from equivalence logic',
  week53AlignmentImpact: 'Automatically excluded from comparable week alignment'
};
